  export const musicLevel = {
    1: "/assets/sounds/musicLevel1.mp3",
    2: "/assets/sounds/musicLevel2.mp3",
    3: "/assets/sounds/musicLevel3.mp3",
    4: "/assets/sounds/musicLevel4.mp3",
    5: "/assets/sounds/musicLevel5.mp3",
    6: "/assets/sounds/musicLevel6.mp3",
    7: "/assets/sounds/musicLevel7.mp3",
    8: "/assets/sounds/musicLevel8.mp3",
    9: "/assets/sounds/musicLevel9.mp3",
    10: "/assets/sounds/musicLevel10.mp3",
    11: "/assets/sounds/musicLevel11.mp3",
    12: "/assets/sounds/musicLevel12.mp3",
    13: "/assets/sounds/musicLevel13.mp3",
    14: "/assets/sounds/musicLevel14.mp3",
    15: "/assets/sounds/musicLevel15.mp3",
    16: "/assets/sounds/musicLevel16.mp3",
    17: "/assets/sounds/musicLevel17.mp3",
  }