  export const syllabeSequence = {
    1: ["BA", "BE", "BI", "BO", "BU"],
    2: ["CA", "CE", "CI", "CO", "CU"],
    3: ["DA", "DE", "DI", "DO", "DU"],
    4: ["FA", "FE", "FI", "FO", "FU"],
    5: ["GA", "GE", "GI", "GO", "GU"],
    6: ["JA", "JE", "JI", "JO", "JU"],
    7: ["KA", "KE", "KI", "KO", "KU"],
    8: ["LA", "LE", "LI", "LO", "LU"],
    9: ["MA", "ME", "MI", "MO", "MU"],
    10: ["NA", "NE", "NI", "NO", "NU"],
    11: ["PA", "PE", "PI", "PO", "PU"],
    12: ["RA", "RE", "RI", "RO", "RU"],
    13: ["SA", "SE", "SI", "SO", "SU"],
    14: ["TA", "TE", "TI", "TO", "TU"],
    15: ["VA", "VE", "VI", "VO", "VU"],
    16: ["YA", "YE", "YI", "YO", "YU"],
    17: ["ZA", "ZE", "ZI", "ZO", "ZU"],
  }